zypper install btrfsprogs
zypper install diffutils
zypper install e2fsprogs
zypper install fdupes
zypper install gcc-c++
zypper install genisoimage
zypper install genisoimage
zypper install libxslt
zypper install lvm2
zypper install module-init-tools
zypper install perl-Class-Singleton
zypper install perl-Config-IniFiles
zypper install perl-Digest-SHA1
zypper install perl-File-Slurp
zypper install perl-JSON
zypper install perl-Readonly
zypper install perl-Test-Unit-Lite
zypper install perl-XML-LibXML
zypper install perl-XML-LibXML-Common
zypper install perl-XML-SAX
zypper install perl-libwww-perl
zypper install rsync
zypper install screen
zypper install squashfs
zypper install syslinux
zypper install zlib-devel
zypper install zypper
